window.LMA_UI = {
    els: {
        // Setup Inputs
        tpressure_f: document.getElementById('tpressure_f'),
        tpressure_r: document.getElementById('tpressure_r'),
        fcam: document.getElementById('fcam'),
        rcam: document.getElementById('rcam'),

        fbd: document.getElementById('fbd'),
        rbd: document.getElementById('rbd'),
        fs: document.getElementById('fs'),
        rs: document.getElementById('rs'),
        fpk: document.getElementById('fpk'),
        rpk: document.getElementById('rpk'),
        fh: document.getElementById('fh'),
        rh: document.getElementById('rh'),
        fsb: document.getElementById('fsb'),
        fsr: document.getElementById('fsr'),
        ffb: document.getElementById('ffb'),
        ffr: document.getElementById('ffr'),
        rsb: document.getElementById('rsb'),
        rsr: document.getElementById('rsr'),
        rfb: document.getElementById('rfb'),
        rfr: document.getElementById('rfr'),
        ftoe: document.getElementById('ftoe'),
        rtoe: document.getElementById('rtoe'),
        farb: document.getElementById('farb'),
        rarb: document.getElementById('rarb'),
        wing: document.getElementById('wing'),
        tender_f: document.getElementById('tender_f'),
        third_Fspring: document.getElementById('third_Fspring'),
        third_fpk: document.getElementById('third_fpk'),
        third_Rspring: document.getElementById('third_Rspring'),
        third_rpk: document.getElementById('third_rpk'),

        // Radar / Visual Targets
        ghostPoly: document.getElementById('ghostPoly'),
        spiderPoly: document.getElementById('spiderPoly'),
        barActiveDf: document.getElementById('barActiveDf'),
        barActiveGr: document.getElementById('barActiveGr'),
        barActiveTu: document.getElementById('barActiveTu'),
        barActiveBu: document.getElementById('barActiveBu'),
        barActiveTs: document.getElementById('barActiveTs'),
        barTargetDf: document.getElementById('barTargetDf'),
        barTargetGr: document.getElementById('barTargetGr'),
        barTargetTu: document.getElementById('barTargetTu'),
        barTargetBu: document.getElementById('barTargetBu'),
        barTargetTs: document.getElementById('barTargetTs'),
        barValDf: document.getElementById('barValDf'),
        barValGr: document.getElementById('barValGr'),
        barValTu: document.getElementById('barValTu'),
        barValBu: document.getElementById('barValBu'),
        barValTs: document.getElementById('barValTs'),

        // Value Readouts (labels)
        tp_fV: document.getElementById('tp_fV'),
        tp_rV: document.getElementById('tp_rV'),
        fcV: document.getElementById('fcV'),
        rcV: document.getElementById('rcV'),
        fbdV: document.getElementById('fbdV'),
        rbdV: document.getElementById('rbdV'),

        fsV: document.getElementById('fsV'),
        rsV: document.getElementById('rsV'),
        fpkV: document.getElementById('fpkV'),
        rpkV: document.getElementById('rpkV'),
        fhV: document.getElementById('fhV'),
        rhV: document.getElementById('rhV'),
        fsbV: document.getElementById('fsbV'),
        fsrV: document.getElementById('fsrV'),
        ffbV: document.getElementById('ffbV'),
        ffrV: document.getElementById('ffrV'),
        rsbV: document.getElementById('rsbV'),
        rsrV: document.getElementById('rsrV'),
        rfbV: document.getElementById('rfbV'),
        rfrV: document.getElementById('rfrV'),
        ftoeV: document.getElementById('ftoeV'),
        rtoeV: document.getElementById('rtoeV'),
        farbV: document.getElementById('farbV'),
        rarbV: document.getElementById('rarbV'),
        wingV: document.getElementById('wingV'),
        tender_fV: document.getElementById('tender_fV'),
        third_FspringV: document.getElementById('third_FspringV'),
        third_fpkV: document.getElementById('third_fpkV'),
        third_RspringV: document.getElementById('third_RspringV'),
        third_rpkV: document.getElementById('third_rpkV'),
        rakeV: document.getElementById('rakeV'),


        // Labels / Containers
        tp_fC_label: document.getElementById('tp_fC_label'),
        tp_rC_label: document.getElementById('tp_rC_label'),
        fcC_label: document.getElementById('fcC_label'),
        rcC_label: document.getElementById('rcC_label'),
        fbdC_label: document.getElementById('fbdC_label'),
        rbdC_label: document.getElementById('rbdC_label'),

        fsC_label: document.getElementById('fsC_label'),
        rsC_label: document.getElementById('rsC_label'),
        fpkC_label: document.getElementById('fpkC_label'),
        rpkC_label: document.getElementById('rpkC_label'),
        fhC_label: document.getElementById('fhC_label'),
        rhC_label: document.getElementById('rhC_label'),
        fsbC_label: document.getElementById('fsbC_label'),
        fsrC_label: document.getElementById('fsrC_label'),
        ffbC_label: document.getElementById('ffbC_label'),
        ffrC_label: document.getElementById('ffrC_label'),
        rsbC_label: document.getElementById('rsbC_label'),
        rsrC_label: document.getElementById('rsrC_label'),
        rfbC_label: document.getElementById('rfbC_label'),
        rfrC_label: document.getElementById('rfrC_label'),
        ftoeC_label: document.getElementById('ftoeC_label'),
        rtoeC_label: document.getElementById('rtoeC_label'),
        farbC_label: document.getElementById('farbC_label'),
        rarbC_label: document.getElementById('rarbC_label'),
        wingC_label: document.getElementById('wingC_label'),
        tender_fC_label: document.getElementById('tender_fC_label'),
        third_FspringC_label: document.getElementById('third_FspringC_label'),
        third_fpkC_label: document.getElementById('third_fpkC_label'),
        third_RspringC_label: document.getElementById('third_RspringC_label'),
        third_rpkC_label: document.getElementById('third_rpkC_label'),

        // Environment UI
        trackTemp: document.getElementById('trackTemp'),
        trackTempV: document.getElementById('trackTempV'),
        weatherChips: document.getElementById('weatherChips'),
        tempPresets: document.getElementById('tempPresets'),

        // Navigation / Menus
        gameLMU: document.getElementById('gameLMU'),
        gameAC: document.getElementById('gameAC'),
        openGarageBtn: document.getElementById('openGarageBtn'),
        modeBasic: document.getElementById('modeBasic'),
        modeAdvanced: document.getElementById('modeAdvanced'),
        currentCar: document.getElementById('currentCar'),
        currentCarClass: document.getElementById('currentCarClass'),
        machineDropdown: document.getElementById('machineDropdown'),
        openTrackBtn: document.getElementById('openTrackBtn'),
        currentTrack: document.getElementById('currentTrack'),
        trackDropdown: document.getElementById('trackDropdown'),
        trackAdvice: document.getElementById('trackAdvice'),

        // Fuel Calculator
        fuelHours: document.getElementById('fuelHours'),
        fuelMinutes: document.getElementById('fuelMinutes'),
        fuelTotalLaps: document.getElementById('fuelTotalLaps'),
        fuelLapMin: document.getElementById('fuelLapMin'),
        fuelLapSec: document.getElementById('fuelLapSec'),
        fuelLapMs: document.getElementById('fuelLapMs'),
        fuelPerLapInput: document.getElementById('fuelPerLapInput'),
        fuelResultLaps: document.getElementById('fuelResultLaps'),
        fuelResultFuel: document.getElementById('fuelResultFuel'),
        fuelResultSafety: document.getElementById('fuelResultSafety'),
        fuelModeTime: document.getElementById('fuelModeTime'),
        fuelModeLaps: document.getElementById('fuelModeLaps'),
        fuelLapsInput: document.getElementById('fuelLapsInput'),
        fuelTimeInputs: document.getElementById('fuelTimeInputs'),
        fuelLapTimeLabel: document.getElementById('fuelLapTimeLabel'),

        // View Toggles
        viewRadar: document.getElementById('viewRadar'),
        viewBars: document.getElementById('viewBars'),
        radarView: document.getElementById('radarView'),
        barsView: document.getElementById('barsView'),

        // Wing Toggle
        wingToggleContainer: document.getElementById('wingToggleContainer'),
        lowDragBtn: document.getElementById('lowDragBtn'),
        highDragBtn: document.getElementById('highDragBtn'),

        // Tyre / Damper Visuals
        tyreFL: document.getElementById('tyreFL'),
        tyreFR: document.getElementById('tyreFR'),
        tyreRL: document.getElementById('tyreRL'),
        tyreRR: document.getElementById('tyreRR'),
        heatFL: document.getElementById('heatFL'),
        heatFR: document.getElementById('heatFR'),
        heatRL: document.getElementById('heatRL'),
        heatRR: document.getElementById('heatRR'),
        dampFL: document.getElementById('dampFL'),
        dampFR: document.getElementById('dampFR'),
        dampRL: document.getElementById('dampRL'),
        dampRR: document.getElementById('dampRR'),

        // Other
        cop: document.getElementById('cop'),
        fP: document.getElementById('fP'),
        rP: document.getElementById('rP'),
        steerStatus: document.getElementById('steerStatus'),
        linkTiresBtn: document.getElementById('linkTiresBtn'),

        saveSetupBtn: document.getElementById('saveSetupBtn'),
        deleteSetupBtn: document.getElementById('deleteSetupBtn'),
        presetContainer: document.getElementById('presetContainer')
    }
};
